name: Run PowerShell Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
    - name: Set PowerShell execution policy
      run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
      shell: pwsh
    - name: Run PowerShell Inline
      run: Write-Output "Running an inline PowerShell command on self-hosted runner"
      shell: pwsh

#      # Run an external PowerShell script
#      - name: Run External PowerShell Script
#        shell: powershell
#        run: ./test.ps1
