name: Run PowerShell Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: self-hosted
    steps:
      # Check out the repository code
      - name: Checkout Code
        uses: actions/checkout@v3

      # Run a simple PowerShell command
      - name: Run PowerShell Inline
        shell: powershell
        run: |
          Write-Output "Running an inline PowerShell command on self-hosted runner"

      # Run the external PowerShell script
      - name: Run External PowerShell Script
        shell: powershell
        run: ./PowerShell/SimpleScript.ps1
