name: Run PowerShell Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Set safe directory
        run: git config --global --add safe.directory C:/actions-runner/_work/githubactions-test/githubactions-test
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set PowerShell execution policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
      - name: Run PowerShell Script
        run: ./PowerShell/SimpleScript.ps1
        shell: powershell
      - name: Run External PowerShell Script2
        shell: powershell
        run: ./PowerShell/SimpleScript2.ps1
      - name: Run Python Script
        run: C:/Programs/Python/Python39/python.exe ./Python/Hello.py