name: Run PowerShell Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set PowerShell execution policy
        run: Set-ExecutionPolicy -ExecutionPolicy Bypass -Scope Process -Force
        shell: powershell
      - name: Run PowerShell Script
        run: ./PowerShell/SimpleScript.ps1
        shell: powershell
      - name: Run External PowerShell Script2
        shell: powershell
        run: ./PowerShell/SimpleScript2.ps1