name: Run PowerShell Script on Self-Hosted Runner

on:
  push:
    branches:
      - main

jobs:
  run-powershell-script:
    runs-on: self-hosted
    steps:
      # Run an inline PowerShell command
      - name: Run PowerShell Inline
        shell: powershell
        run: Write-Output "Running an inline PowerShell command on self-hosted runner"

#      # Run an external PowerShell script
#      - name: Run External PowerShell Script
#        shell: powershell
#        run: ./test.ps1
