name: test_1 Workflow

on:
  workflow_dispatch:
  schedule:
    - cron: '46 11 * * *'

jobs:
  print-message:
    runs-on: ubuntu-latest
    steps:
      - name: Print message
        run: echo "Hello from test_1 workflow!"
      - name: Print execution time (UTC)
        run: date -u